DROP DATABASE IF EXISTS diyWriters;
CREATE DATABASE diyWriters;
USE diyWriters;

CREATE TABLE user(
Id INT NOT NULL AUTO_INCREMENT,
UserName VARCHAR(50) NOT NULL UNIQUE,
Password VARCHAR(50) NOT NULL,
FirstName VARCHAR(75) NOT NULL,
LastName VARCHAR(75) NOT NULL,
Bio VARCHAR(500) NOT NULL,
Email VARCHAR(75) UNIQUE,
Phone VARCHAR(12),
Admin BIT(1) NOT NULL
);

CREATE TABLE Piece(
Id INT NOT NULL AUTO_INCREMENT,
UserId INT NOT NULL,
Title VARCHAR(100) NOT NULL,
Genre VARCHAR(25) NOT NULL,
FileName VARCHAR(100) NOT NULL,
File BLOB NOT NULL,
Submitted DATETIME NOT NULL);

GRANT SELECT, INSERT, DELETE, UPDATE
ON diyWriters.*
TO diy_user@localhost
IDENTIFIED BY 'writethings';