DROP DATABASE IF EXISTS diyWriters;
CREATE DATABASE diyWriters;
USE diyWriters;

CREATE TABLE User(
Id INT PRIMARY KEY AUTO_INCREMENT,
UserName VARCHAR(50) NOT NULL UNIQUE,
Password VARCHAR(50) NOT NULL,
FirstName VARCHAR(75) NOT NULL,
LastName VARCHAR(75) NOT NULL,
Bio VARCHAR(500) NOT NULL,
Email VARCHAR(75) UNIQUE,
Phone VARCHAR(12),
IsAdmin TINYINT(1) DEFAULT 0 NOT NULL
);


CREATE TABLE Piece(
Id INT PRIMARY KEY AUTO_INCREMENT,
UserId INT NOT NULL,
Title VARCHAR(100) NOT NULL,
Genre VARCHAR(25) NOT NULL,
FileName VARCHAR(175) NOT NULL,
Submitted DATETIME NOT NULL DEFAULT NOW(),

Foreign Key (UserID) references User(ID)
);

CREATE USER IF NOT EXISTS 'diy_user'@'localhost' IDENTIFIED BY 'writethings';

GRANT SELECT, INSERT, DELETE, UPDATE
ON diyWriters.*
TO diy_user@localhost;